import {test,expect} from '@playwright/test';
import path from 'node:path';
test('all five screens, presets, and responsive layout', async ({page})=>{
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Every plate. Every sampled moment.'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Start processing'})).toBeDisabled();
  await page.getByRole('button',{name:'Local paths',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'File or folder paths'})).toBeVisible();
  await page.getByRole('combobox',{name:'Image mode',exact:true}).selectOption('crop');
  await expect(page.getByRole('combobox',{name:'Process through',exact:true})).not.toHaveText(/Detection only/);
  await page.getByRole('button',{name:'Review',exact:true}).click();
  await expect(page.getByText('Select a job or start an analysis.')).toBeVisible();
  await page.getByRole('button',{name:'History',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Saved jobs',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Pipeline / Settings',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Runtime and model readiness'})).toBeVisible();
  await page.getByLabel('Preset name',{exact:true}).fill('Browser verification');
  await page.getByRole('button',{name:'Add preset',exact:true}).click();
  await expect(page.getByText('Preset added. Save settings to persist it.')).toBeVisible();
  await page.getByRole('button',{name:'Remove',exact:true}).click();
  await page.getByRole('button',{name:'Accuracy',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Original versus enhanced OCR'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Analyze',exact:true}).click();
  await expect(page.getByRole('button',{name:'Start processing'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path:'../.runtime/analyze-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'../.runtime/analyze-desktop.png',fullPage:true});
  expect(errors).toEqual([]);
});

test('upload a real crop, review Arabic output, and preserve correction history', async ({page})=>{
  await page.goto('/');
  await page.getByRole('combobox',{name:'Image mode',exact:true}).selectOption('crop');
  await page.locator('input[type="file"]').first().setInputFiles(path.resolve('../.runtime/verification-media/plate-001.png'));
  await page.getByRole('button',{name:'Start processing',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Processing complete',exact:true})).toBeVisible({timeout:60000});
  const card=page.locator('.detection-card').first();
  await expect(card.getByRole('img',{name:'Original plate crop',exact:true})).toBeVisible();
  await expect(card.getByRole('img',{name:'Enhanced plate crop',exact:true})).toBeVisible();
  await expect(card.locator('.plate-display bdi[dir="rtl"]')).not.toHaveText('—');
  await card.getByText('Correct reading / prediction history',{exact:true}).click();
  await card.getByRole('textbox',{name:'Corrected reading',exact:true}).fill('123 مسب');
  await card.getByRole('textbox',{name:'Review note',exact:true}).fill('Browser verification');
  await card.getByRole('button',{name:'Save correction',exact:true}).click();
  await expect(card.locator('.plate-display')).toHaveText('123 مسب');
  await card.getByRole('button',{name:'Load history',exact:true}).click();
  await expect(card.locator('.audit-history')).toContainText('Browser verification');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'../.runtime/review-desktop.png',fullPage:true});
});
