import {useCallback, useEffect, useState} from 'react';
import {Activity, ArrowRight, Download, Eye, FolderOpen, History, ScanLine, Settings, ShieldCheck, UploadCloud} from './icons';
import {active, api, artifact, defaults, percent} from './api';
import type {Detection, Health, Job, Options, Run} from './api';
import OptionsForm from './OptionsForm';
import AuditHistory from './AuditHistory';
import type {Audit} from './AuditHistory';

const tabs = ['Analyze','Review','History','Pipeline / Settings','Accuracy'] as const;
type Tab = typeof tabs[number];

function Progress({job}: {job: Job}) {
  const p = job.progress;
  return <div className="panel padded progress-panel"><div className="section-heading"><h3>{job.stage === 'complete' ? 'Processing complete' : `${job.stage} · ${job.status}`}</h3><span className={`badge ${job.status}`}>{job.counts.detections} detections</span></div><div className="stage-track">{['detect','enhance','ocr'].map((stage,i)=><span key={stage} className={job.stage === stage ? 'current' : ''}>{i+1}. {stage === 'detect' ? 'Detection' : stage === 'enhance' ? 'Enhancement' : 'Recognition'}</span>)}</div>{active(job) && <progress max={p.total || 1} value={p.done || 0}/>}<p className="subtle">{p.done || 0}{p.total ? ` / ${p.total}` : ''} {p.sampled_frames != null ? ` · ${p.sampled_frames} sampled frames` : ''} {p.source && ` · ${p.source}`}</p>{job.error && <p className="error" role="alert">{job.error}</p>}</div>;
}

function Card({item, changed, report}: {item: Detection; changed: ()=>void; report: (error: unknown)=>void}) {
  const [text,setText] = useState(item.corrected_text ?? `${item.digits || ''} ${item.arabic_letters || ''}`.trim());
  const [note,setNote] = useState('');
  const [audit,setAudit] = useState<Audit|null>(null);
  async function save() {try {await api(`/detections/${item.id}/correction`, {text,note}); changed();} catch(error) {report(error);}}
  return <article className="panel padded detection-card"><div className="section-heading"><span className="source-title">{item.source_name}</span><span className={`badge ${item.needs_review ? 'warning' : 'completed'}`}>{item.needs_review ? 'Needs review' : 'Reviewed / clear'}</span></div>
    <div className="crop-pair"><figure><img src={artifact(item.job_id,item.original)} alt="Original plate crop"/><figcaption>Original · lossless PNG</figcaption></figure><figure>{item.enhanced ? <img src={artifact(item.job_id,item.enhanced)} alt="Enhanced plate crop"/> : <div className="crop-placeholder">Enhancement pending</div>}<figcaption>Enhanced {item.enhancement && `· ${item.enhancement.upscale}× · ${item.enhancement.method.replaceAll('_',' ')}`}</figcaption></figure></div>
    <div className="plate-display">{item.corrected_text != null ? <bdi dir="auto">{item.corrected_text || '(empty correction)'}</bdi> : <><bdi dir="ltr">{item.digits || '—'}</bdi> <bdi dir="rtl">{item.arabic_letters || '—'}</bdi></>}</div><p className="subtle">Raw OCR: <bdi dir="auto">{item.raw_text ?? 'Not recognized yet'}</bdi></p>
    <dl className="metrics"><div><dt>Detector confidence</dt><dd>{percent(item.detector_confidence)}</dd></div><div><dt>Crop quality</dt><dd>{percent(item.quality.quality_score)}</dd></div><div><dt>OCR confidence</dt><dd>{percent(item.ocr_confidence)}</dd></div><div><dt>Frame / time</dt><dd>{item.frame_index} / {item.timestamp.toFixed(3)}s</dd></div></dl>
    {item.review_flags.length > 0 && <div className="flag-row">{item.review_flags.map(flag=><span key={flag}>{flag}</span>)}</div>}
    <div className="button-row"><a className="secondary" href={artifact(item.job_id,item.source_frame)} target="_blank" rel="noreferrer">Inspect source frame <Eye size={14}/></a><details><summary>Quality measurements</summary><dl className="quality-details">{Object.entries(item.quality).filter(([key])=>key !== 'flags').map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof value === 'number' ? value.toFixed(2) : String(value)}</dd></div>)}</dl></details></div>
    {item.comparison && <div className="comparison"><p>Truth (visual order): <bdi>{item.comparison.truth}</bdi></p><p>Original OCR: <bdi>{item.comparison.original.raw_text}</bdi> · {percent(item.comparison.original.ocr_confidence)}</p><p>Enhanced OCR: <bdi>{item.comparison.enhanced.raw_text}</bdi> · {percent(item.comparison.enhanced.ocr_confidence)}</p></div>}
    <details className="correction"><summary>Correct reading / prediction history</summary><div className="field-row"><label>Corrected reading<input value={text} dir="auto" onChange={e=>setText(e.target.value)}/></label><label>Review note<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><div className="button-row"><button className="primary" onClick={save}>Save correction</button><button className="secondary" onClick={()=>api<Audit>(`/detections/${item.id}/history`).then(setAudit).catch(report)}>Load history</button></div>{audit && <AuditHistory audit={audit} jobId={item.job_id}/>}</details>
  </article>;
}

export default function App() {
  const [tab,setTab] = useState<Tab>('Analyze');
  const [options,setOptions] = useState<Options>(defaults);
  const [presets,setPresets] = useState<Record<string,Options>>({});
  const [presetName,setPresetName] = useState('');
  const [health,setHealth] = useState<Health>({state:'connecting',device:'',stages:{}});
  const [jobs,setJobs] = useState<Job[]>([]);
  const [jobsTotal,setJobsTotal] = useState(0);
  const [historyOffset,setHistoryOffset] = useState(0);
  const [selected,setSelected] = useState<Job|null>(null);
  const [detections,setDetections] = useState<Detection[]>([]);
  const [total,setTotal] = useState(0);
  const [offset,setOffset] = useState(0);
  const [source,setSource] = useState('');
  const [review,setReview] = useState(false);
  const [maxConfidence,setMaxConfidence] = useState('');
  const [paths,setPaths] = useState('');
  const [recursive,setRecursive] = useState(false);
  const [files,setFiles] = useState<File[]>([]);
  const [inputMode,setInputMode] = useState<'upload'|'path'>('upload');
  const [manifest,setManifest] = useState('');
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  const [notice,setNotice] = useState('');
  const report = useCallback((err: unknown)=>setError(err instanceof Error ? err.message : String(err)),[]);
  const loadJobs = useCallback(()=>api<{items: Job[];total:number}>(`/jobs?offset=${historyOffset}`).then(data=>{setJobs(data.items);setJobsTotal(data.total);}).catch(report),[historyOffset,report]);
  const loadDetections = useCallback(()=>{if (!selected) return; const query = new URLSearchParams({offset:String(offset),limit:'30'}); if(source)query.set('source',source);if(review)query.set('review','true');if(maxConfidence)query.set('max_confidence',maxConfidence);api<{items:Detection[];total:number}>(`/jobs/${selected.id}/detections?${query}`).then(data=>{setDetections(data.items);setTotal(data.total);}).catch(report);},[selected?.id,offset,source,review,maxConfidence,report]);
  useEffect(()=>{api<{defaults: Options; presets: Record<string,Options>}>('/settings').then(data=>{setOptions(data.defaults);setPresets(data.presets);}).catch(report);},[report]);
  useEffect(()=>{loadJobs(); const timer=setInterval(loadJobs,5000);return()=>clearInterval(timer);},[loadJobs]);
  useEffect(()=>{const update=()=>api<Health>('/health').then(setHealth).catch(report);update(); const timer=setInterval(update,5000);return()=>clearInterval(timer);},[report]);
  useEffect(()=>{loadDetections();},[loadDetections]);
  useEffect(()=>{if (!selected || !active(selected)) return;const stream=new EventSource(`/api/jobs/${selected.id}/events`);stream.onmessage=e=>{const job=JSON.parse(e.data) as Job;setSelected(job);if (!active(job)) {stream.close();loadDetections();loadJobs();api<Job>(`/jobs/${job.id}`).then(setSelected).catch(report);}};return()=>stream.close();},[selected?.id,selected?.status,loadDetections,loadJobs,report]);
  const choose = (job:Job, nextTab:Tab='Review')=>{setSelected(job);setOffset(0);setSource('');setReview(false);setMaxConfidence('');setTab(nextTab);api<Job>(`/jobs/${job.id}`).then(setSelected).catch(report);};
  async function perform(action: ()=>Promise<unknown>) {setBusy(true);setError('');setNotice('');try {await action();}catch(err){report(err);}finally{setBusy(false);}}
  async function start() {await perform(async()=>{let job:Job;if(inputMode==='path'){job=await api<Job>('/jobs/paths',{paths:paths.split('\n').map(p=>p.trim()).filter(Boolean),recursive,options});}else{const form=new FormData();files.forEach(file=>form.append('files',file,file.webkitRelativePath || file.name));form.append('options',JSON.stringify(options));const response=await fetch('/api/jobs/upload',{method:'POST',body:form});const body=await response.json();if(!response.ok)throw new Error(typeof body.detail === 'string' ? body.detail : JSON.stringify(body.detail));job=body;}choose(job);loadJobs();});}
  const mutateJob = (action:string,body?:unknown)=>selected && perform(async()=>{const job=await api<Job>(`/jobs/${selected.id}/${action}`,body ?? {});setSelected(job);loadJobs();});
  async function download(kind:string) {if(!selected)return;await perform(async()=>{const response=await fetch(`/api/jobs/${selected.id}/export/${kind}`);if(!response.ok){const body=await response.json();throw new Error(body.detail || response.statusText);}const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=`iris-${selected.id.slice(0,8)}-${kind}.${['csv','json'].includes(kind)?kind:'zip'}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
  const saveSettings = ()=>perform(async()=>{await api('/settings',{defaults:options,presets},'PUT');setNotice('Processing defaults and presets saved.');});
  return <><header className="standalone-header"><ScanLine size={24}/><strong>IRIS Pipeline</strong><span>License plate processing</span><div className={`runtime-pill ${health.state === 'ready'?'online':''}`}><span/> {health.device || health.state}</div></header><main className="workspace page-stack">
    <section className="panel hero"><div><div className="kicker">DETECT · ENHANCE · RECOGNIZE</div><h1>Every plate. Every sampled moment.</h1><p className="subtle">Inspect each stage, review Arabic readings, and keep the evidence.</p></div><ScanLine size={64}/></section>
    <nav className="tabs" aria-label="Workspace">{tabs.map((name,i)=>{const Icon=[ScanLine,Eye,History,Settings,ShieldCheck][i];return <button key={name} className={tab===name?'active':''} onClick={()=>{setTab(name);setError('');}}><Icon size={16}/>{name}</button>;})}</nav>
    {error && <div className="error panel padded" role="alert">{error}<button className="dismiss" onClick={()=>setError('')}>Dismiss</button></div>}{notice && <div className="notice panel padded" role="status">{notice}</div>}
    {tab==='Analyze' && <section className="panel padded"><div className="section-heading"><div><h2>Start an analysis</h2><p className="subtle">Images, videos, or a whole folder. All detections are retained.</p></div><select aria-label="Processing preset" value="" onChange={e=>setOptions(presets[e.target.value] || options)}><option value="">Apply a saved preset</option>{Object.keys(presets).map(name=><option key={name}>{name}</option>)}</select></div><div className="button-row"><button className={inputMode==='upload'?'primary':'secondary'} onClick={()=>setInputMode('upload')}><UploadCloud size={16}/>Upload media</button><button className={inputMode==='path'?'primary':'secondary'} onClick={()=>setInputMode('path')}><FolderOpen size={16}/>Local paths</button></div>
      {inputMode==='upload' ? <div className="upload-zone"><UploadCloud size={30}/><p>Choose image/video files or a folder</p><div className="field-row"><label>Files<input type="file" multiple accept="image/*,video/*" onChange={e=>setFiles(Array.from(e.target.files || []))}/></label><label>Folder<input type="file" multiple {...{webkitdirectory:'',directory:''}} onChange={e=>setFiles(Array.from(e.target.files || []).filter(f=>/\.(jpe?g|png|bmp|webp|tiff?|mp4|avi|mov|mkv|m4v|wmv|flv|webm)$/i.test(f.name)))}/></label></div><small>{files.length} supported files selected</small></div> : <><label>File or folder paths · one per line<textarea rows={4} value={paths} onChange={e=>setPaths(e.target.value)} placeholder={'C:\\camera\\recording.mp4\nC:\\camera\\images'}/></label><label className="check"><input type="checkbox" checked={recursive} onChange={e=>setRecursive(e.target.checked)}/>Include subfolders</label><p className="subtle">Paths refer to files on the computer running IRIS Pipeline.</p></>}
      <OptionsForm value={options} change={setOptions}/><div className="button-row"><button className="primary" disabled={busy || (inputMode==='upload' ? !files.length : !paths.trim())} onClick={start}>{busy?'Submitting…':'Start processing'}<ArrowRight size={16}/></button><span className="subtle">One inference job at a time · later jobs are queued</span></div></section>}
    {tab==='Review' && <><div className="panel padded section-heading"><label>Job<select value={selected?.id || ''} onChange={e=>{const job=jobs.find(j=>j.id===e.target.value);if(job)choose(job);}}><option value="">Select a saved job</option>{jobs.map(job=><option key={job.id} value={job.id}>{job.sources[0]?.name.split(/[\\/]/).pop()} · {job.id.slice(0,8)} · {job.status}</option>)}</select></label>{selected && <div className="button-row"><button className="secondary" disabled={busy || active(selected)} onClick={()=>mutateJob('rerun',{stage:'enhance',options})}>Rerun enhancement</button><button className="secondary" disabled={busy || active(selected)} onClick={()=>mutateJob('rerun',{stage:'ocr'})}>Rerun OCR</button></div>}</div>{selected ? <><Progress job={selected}/><div className="panel padded field-row three"><label>Source<select value={source} onChange={e=>{setSource(e.target.value);setOffset(0);}}><option value="">All sources</option>{selected.sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Maximum OCR confidence<input type="number" placeholder="All readings" min="0" max="1" step="0.05" value={maxConfidence} onChange={e=>{setMaxConfidence(e.target.value);setOffset(0);}}/></label><label className="check"><input type="checkbox" checked={review} onChange={e=>{setReview(e.target.checked);setOffset(0);}}/>Needs review only</label></div><div className="section-heading"><p className="subtle">{total} detections · showing {total ? offset+1 : 0}–{Math.min(offset+30,total)}</p><button className="secondary" onClick={loadDetections}>Refresh results</button></div><div className="results">{detections.map(item=><Card key={`${item.id}-${item.raw_text}`} item={item} changed={loadDetections} report={report}/>)}</div>{!detections.length && <div className="panel empty"><Eye/><p>{active(selected)?'Results appear as crops are saved.':'No detections match this view.'}</p></div>}<div className="button-row"><button className="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-30))}>Previous</button><button className="secondary" disabled={offset+30>=total} onClick={()=>setOffset(offset+30)}>Next</button></div></> : <div className="panel empty"><Eye/><p>Select a job or start an analysis.</p></div>}</>}
    {tab==='History' && <section className="panel padded"><div className="section-heading"><h2>Saved jobs</h2><button className="secondary" onClick={loadJobs}>Refresh</button></div><div className="history-list">{jobs.map(job=><div className="history-row" key={job.id}><button className="job-main" onClick={()=>choose(job)}><strong>{job.sources[0]?.name.split(/[\\/]/).pop() || job.id}</strong><span>{new Date(job.created).toLocaleString()} · {job.sources.length} sources · {job.counts.detections} detections · {job.kind}</span></button><span className={`badge ${job.status}`}>{job.status}</span>{active(job) && <button className="secondary" onClick={()=>perform(async()=>{await api(`/jobs/${job.id}/cancel`,{});loadJobs();})}>Cancel</button>}{['failed','cancelled'].includes(job.status) && <button className="secondary" onClick={()=>perform(async()=>{choose(await api<Job>(`/jobs/${job.id}/retry`,{}));loadJobs();})}>Retry</button>}<button className="secondary" onClick={()=>{choose(job,'History');}}>Artifacts</button></div>)}</div>{!jobs.length && <p className="subtle">Your first analysis will appear here.</p>}<div className="button-row"><button className="secondary" disabled={historyOffset===0} onClick={()=>setHistoryOffset(Math.max(0,historyOffset-50))}>Previous</button><span className="subtle">{jobsTotal} saved jobs</span><button className="secondary" disabled={historyOffset+50>=jobsTotal} onClick={()=>setHistoryOffset(historyOffset+50)}>Next</button></div>{selected && <div className="artifact-box"><h3>Artifacts · {selected.id.slice(0,8)}</h3><Progress job={selected}/><div className="button-row">{['csv','json','crops','annotated'].map(kind=><button className="secondary" key={kind} disabled={busy || active(selected)} onClick={()=>download(kind)}><Download size={14}/>{kind==='crops'?'Crop ZIP':kind==='annotated'?'Annotated media':kind.toUpperCase()}</button>)}</div><details><summary>Stage timings and runs</summary>{selected.runs?.map((run:Run)=><p className="subtle" key={run.id}>{run.created} · {run.stage} · {run.status} · {Object.entries(run.timings).map(([stage,seconds])=>`${stage}: ${seconds.toFixed(2)}s`).join(' · ')} · {run.detections_per_second?.toFixed(2)} detections/s</p>)}</details></div>}</section>}
    {tab==='Pipeline / Settings' && <><section className="panel padded"><div className="section-heading"><h2>Runtime and model readiness</h2><button className="secondary" onClick={()=>perform(async()=>{await api('/diagnostics',{});setNotice('Diagnostics queued. Readiness will update after the checks finish.');})}><Activity size={16}/>Check inference</button></div><p className="subtle">{health.gpu ? `${health.gpu.name} · ${(health.gpu.vram_bytes/2**30).toFixed(1)} GB VRAM · compute ${health.gpu.compute_capability}` : `Device: ${health.device || 'checking'}`} · PyTorch {health.torch || 'checking'}</p><div className="preflight">{['detect','enhance','ocr'].map(stage=><div key={stage} className="runtime-card"><strong>{stage==='detect'?'YOLO detection':stage==='enhance'?'Crop enhancement':'Arabic PP-OCRv5 mobile'}</strong><span className={health.stages[stage]?.ready?'success':'warning'}>{health.stages[stage]?.ready?'Inference verified':health.stages[stage]?.error || 'Checking…'}</span></div>)}</div></section><section className="panel padded"><h2>Processing defaults</h2><OptionsForm value={options} change={setOptions} advanced/><div className="field-row"><label>Preset name<input value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="Camera 01 · night"/></label><div className="button-row"><button className="secondary" disabled={!presetName.trim()} onClick={()=>{setPresets({...presets,[presetName.trim()]:options});setNotice('Preset added. Save settings to persist it.');}}>Add preset</button><button className="primary" disabled={busy} onClick={saveSettings}>Save settings</button></div></div>{Object.keys(presets).map(name=><div className="preset-row" key={name}><span>{name}</span><button className="secondary" onClick={()=>setOptions(presets[name])}>Apply</button><button className="secondary" onClick={()=>setPresets(Object.fromEntries(Object.entries(presets).filter(([key])=>key!==name)))}>Remove</button></div>)}</section></>}
    {tab==='Accuracy' && <><section className="panel padded"><h2>Original versus enhanced OCR</h2><p className="subtle">Use labeled plate crops to compare both readings from the same image. Labels use the model’s visual left-to-right order.</p><label>Local benchmark manifest (JSON)<input value={manifest} onChange={e=>setManifest(e.target.value)} placeholder="C:\\samples\\labels.json"/></label><details><summary>Manifest format</summary><pre>{JSON.stringify([{path:'plate-01.png',truth:'123بسم'}],null,2)}</pre><p className="subtle">Image paths may be relative to the manifest. Truth matches raw CTC output order; Scoring normalizes whitespace, decimal digits, and Arabic aliases (أ/إ/آ → ا, ى → ي, ة → ه).</p></details><div className="button-row"><button className="primary" disabled={busy || !manifest.trim()} onClick={()=>perform(async()=>{const job=await api<Job>('/benchmarks',{manifest_path:manifest,options});choose(job,'Accuracy');loadJobs();})}>Run comparison<ShieldCheck size={16}/></button><select aria-label="Saved benchmark" value={selected?.kind==='benchmark'?selected.id:''} onChange={e=>{const job=jobs.find(j=>j.id===e.target.value);if(job)choose(job,'Accuracy');}}><option value="">Open a saved benchmark</option>{jobs.filter(j=>j.kind==='benchmark').map(j=><option value={j.id} key={j.id}>{new Date(j.created).toLocaleString()} · {j.status}</option>)}</select></div></section>{selected?.kind==='benchmark' && <><Progress job={selected}/>{selected.benchmark && <section className="panel padded"><div className="benchmark-grid">{(['original','enhanced'] as const).map(variant=><div key={variant}><h3>{variant==='original'?'Original crops':'Enhanced crops'}</h3><dl className="metrics"><div><dt>Normalized exact match</dt><dd>{percent(selected.benchmark![variant].exact_match_accuracy)}</dd></div><div><dt>Character error rate</dt><dd>{percent(selected.benchmark![variant].character_error_rate)}</dd></div><div><dt>Edit similarity</dt><dd>{percent(selected.benchmark![variant].normalized_edit_similarity)}</dd></div><div><dt>Samples</dt><dd>{selected.benchmark![variant].samples}</dd></div></dl></div>)}</div><button className="secondary" onClick={()=>{setTab('Review');loadDetections();}}>Inspect sample predictions</button></section>}</>}<p className="subtle">The supplied archive reports 45.1% exact match on 164 held-out images. This is a training report, separate from results measured here.</p></>}
  </main></>;
}
